/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lionscheduler;

/**
 *
 * @author mch5367
 */
public class professorPreferenceScreen extends javax.swing.JFrame {

    /**
     * Creates new form professorPreferenceScreen
     */
    public professorPreferenceScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jlPreferences = new javax.swing.JLabel();
        jlDepartment = new javax.swing.JLabel();
        jlDay = new javax.swing.JLabel();
        jlTime = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jcbMonday = new javax.swing.JCheckBox();
        jcbTuesday = new javax.swing.JCheckBox();
        jcbWednesday = new javax.swing.JCheckBox();
        jcbThursday = new javax.swing.JCheckBox();
        jcbFriday = new javax.swing.JCheckBox();
        jcbSaturday = new javax.swing.JCheckBox();
        jcbSunday = new javax.swing.JCheckBox();
        jlMonday = new javax.swing.JLabel();
        jlTuesday = new javax.swing.JLabel();
        jlWednesday = new javax.swing.JLabel();
        jlThursday = new javax.swing.JLabel();
        jlFriday = new javax.swing.JLabel();
        jlSaturday = new javax.swing.JLabel();
        jlSunday = new javax.swing.JLabel();
        jtfTime = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlPreferences.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlPreferences.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPreferences.setText("Preferences");
        jlPreferences.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlDepartment.setText("Department :");

        jlDay.setText("Day :");

        jlTime.setText("Time :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IST", "SRA", "Engineering", "Business", "History" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jcbMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMondayActionPerformed(evt);
            }
        });

        jcbTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTuesdayActionPerformed(evt);
            }
        });

        jcbWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbWednesdayActionPerformed(evt);
            }
        });

        jcbThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbThursdayActionPerformed(evt);
            }
        });

        jcbFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFridayActionPerformed(evt);
            }
        });

        jcbSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSaturdayActionPerformed(evt);
            }
        });

        jcbSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSundayActionPerformed(evt);
            }
        });

        jlMonday.setText("M");

        jlTuesday.setText("T");

        jlWednesday.setText("W");

        jlThursday.setText("Th");

        jlFriday.setText("F");

        jlSaturday.setText("S");

        jlSunday.setText("Sun");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlPreferences, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTime)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlDepartment)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlDay)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jcbMonday))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlMonday)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jlTuesday)
                                .addGap(18, 18, 18)
                                .addComponent(jlWednesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jlThursday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlFriday)
                                .addGap(18, 18, 18)
                                .addComponent(jlSaturday)
                                .addGap(30, 30, 30)
                                .addComponent(jlSunday))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTime, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jcbTuesday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbWednesday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbThursday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbFriday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbSaturday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbSunday)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlPreferences, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDepartment)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jlDay)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMonday)
                            .addComponent(jlTuesday)
                            .addComponent(jlWednesday)
                            .addComponent(jlThursday)
                            .addComponent(jlFriday)
                            .addComponent(jlSaturday)
                            .addComponent(jlSunday))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbMonday, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbTuesday, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbWednesday, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbThursday, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbFriday, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbSaturday, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbSunday, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTime)
                    .addComponent(jtfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jcbMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMondayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMondayActionPerformed

    private void jcbTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTuesdayActionPerformed

    private void jcbWednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbWednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbWednesdayActionPerformed

    private void jcbThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbThursdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbThursdayActionPerformed

    private void jcbFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFridayActionPerformed

    private void jcbSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSaturdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSaturdayActionPerformed

    private void jcbSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSundayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(professorPreferenceScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(professorPreferenceScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(professorPreferenceScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(professorPreferenceScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new professorPreferenceScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbFriday;
    private javax.swing.JCheckBox jcbMonday;
    private javax.swing.JCheckBox jcbSaturday;
    private javax.swing.JCheckBox jcbSunday;
    private javax.swing.JCheckBox jcbThursday;
    private javax.swing.JCheckBox jcbTuesday;
    private javax.swing.JCheckBox jcbWednesday;
    private javax.swing.JLabel jlDay;
    private javax.swing.JLabel jlDepartment;
    private javax.swing.JLabel jlFriday;
    private javax.swing.JLabel jlMonday;
    private javax.swing.JLabel jlPreferences;
    private javax.swing.JLabel jlSaturday;
    private javax.swing.JLabel jlSunday;
    private javax.swing.JLabel jlThursday;
    private javax.swing.JLabel jlTime;
    private javax.swing.JLabel jlTuesday;
    private javax.swing.JLabel jlWednesday;
    private javax.swing.JTextField jtfTime;
    // End of variables declaration//GEN-END:variables
}
